# variables.tf for the Staging Environment
# Defines all input variables required to configure the staging infrastructure.

variable "project_name" {
  description = "The name of the project, used for resource naming and tagging."
  type        = string
}

variable "environment" {
  description = "The name of the environment (e.g., 'staging')."
  type        = string
  default     = "staging"
}

variable "aws_region" {
  description = "The AWS region to deploy infrastructure into."
  type        = string
}

# ------------------------------------
# VPC Configuration
# ------------------------------------

variable "vpc_cidr" {
  description = "The CIDR block for the VPC."
  type        = string
}

variable "vpc_availability_zones_count" {
  description = "The number of Availability Zones to use for the VPC subnets."
  type        = number
  default     = 2
}

variable "vpc_private_subnets" {
  description = "A list of CIDR blocks for private subnets."
  type        = list(string)
}

variable "vpc_public_subnets" {
  description = "A list of CIDR blocks for public subnets."
  type        = list(string)
}

# ------------------------------------
# EKS Cluster Configuration
# ------------------------------------

variable "eks_cluster_version" {
  description = "The Kubernetes version for the EKS cluster."
  type        = string
}

variable "eks_general_node_instance_types" {
  description = "Instance types for the general purpose EKS node group."
  type        = list(string)
}

variable "eks_general_node_min_size" {
  description = "Minimum number of nodes for the general purpose node group."
  type        = number
}

variable "eks_general_node_max_size" {
  description = "Maximum number of nodes for the general purpose node group."
  type        = number
}

variable "eks_general_node_desired_size" {
  description = "Desired number of nodes for the general purpose node group."
  type        = number
}

# ------------------------------------
# RDS PostgreSQL Configuration
# ------------------------------------

variable "rds_postgres_engine_version" {
  description = "The PostgreSQL engine version for RDS."
  type        = string
}

variable "rds_postgres_instance_class" {
  description = "The instance class for the RDS PostgreSQL instance."
  type        = string
}

variable "rds_postgres_allocated_storage" {
  description = "The allocated storage in GB for the RDS PostgreSQL instance."
  type        = number
}

variable "rds_postgres_username" {
  description = "The master username for the RDS PostgreSQL database. The password will be auto-generated by AWS Secrets Manager."
  type        = string
}

variable "rds_postgres_db_name" {
  description = "The initial database name for the RDS PostgreSQL instance."
  type        = string
}

# ------------------------------------
# ElastiCache Redis Configuration
# ------------------------------------

variable "redis_engine_version" {
  description = "The Redis engine version."
  type        = string
}

variable "redis_node_type" {
  description = "The node type for the Redis cache nodes."
  type        = string
}

variable "redis_num_cache_nodes" {
  description = "The number of cache nodes in the Redis cluster."
  type        = number
}