apiVersion: v2
name: application
description: A generic Helm chart for deploying microservices and frontend applications.

# A chart can be either an 'application' or a 'library' chart.
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version is not necessary
# for charts representing collections of templates, like this one.
appVersion: "1.0.0"